### ISSUE TITLE
Put the cherry back below the ice!

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#57] opened 2017-02-20 21:42 UTC
Why did you rearrange the placement of the cherry in anti gravity aquarium???  I loved how the vine going up to the empty room throws the player off, when the cherry was originally UNDER the ice.  Might I suggest putting a fire flower up in the room?  This way if the player takes the time to find something to hit the box with the vine, it will reward them with firepower to melt the ice below and finally get the cherry.  As it stands now, the secret under the ice leads to nothing.  
![img_2675](https://cloud.githubusercontent.com/assets/6308005/23142765/9a235b1c-f78b-11e6-8200-006eb233f7b6.JPG)
![img_2676](https://cloud.githubusercontent.com/assets/6308005/23142766/9a3956ec-f78b-11e6-9027-f43fd503d556.JPG)

**Comment by dahrkdaiz** [comment] 2017-02-21 02:24
Actually, there was supposed to be a hidden Star where the cherry was before underwater.

**Comment by dahrkdaiz** [comment] 2017-02-21 02:25
Oh woops, there IS a magic star that's supposed to be there, but it was a duplicate of the first so if you collected the first, it wouldn't appear.

**Comment by RetroMarine** [comment] 2017-02-21 02:37
Ahhhhh I see

**Closed** 2017-02-25 12:00 UTC
