### ISSUE TITLE
Hammer Power-up Doesn't Break Bricks with Items

### ISSUE THREAD

**Issue by KingKoopa94** [dahrkdaiz/smb3project#2] opened 2016-12-01 18:33 UTC
I noticed today while playing with the Hammer Bro costume that the hammer will not break bricks that contain an item. It will break regular bricks without an issue, but just passes right through "?" blocks and brick blocks that contain items.

Video showing the issue here:
https://www.youtube.com/watch?v=p8cvxChLYCI

**Comment by dahrkdaiz** [comment] 2016-12-01 22:07
This is actually by design. Breaking a brick in game is relative simple, but activate a ? block is code that doesn't exist in the same area as the hammer projectile code and is unreachable, unfortunately.

**Comment by KingKoopa94** [comment] 2016-12-01 22:48
But turtles can do it.. I know it's very unlikely, but is there a way the turtle's impact code could be used?

**Comment by EdGe7x** [comment] 2016-12-02 03:09
I think the difference between the turtle action and the hammer action is that the hammer is meant to destroy a block. The turtle shell activates the block. It does look funny just watching the hammer fly right through them but if anything is implemented it should be that the hammer also destroys the block as an unintended consequence of using the hammer power on all blocks indiscriminately. Just my 2 cents.

**Comment by dahrkdaiz** [comment] 2016-12-02 11:21
You guys all make good points! I was surprising able to figure out a way to make this work. This is now fixed.

**Closed** 2016-12-02 11:21 UTC
