### ISSUE TITLE
Vine randomly choppy or split

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#41] opened 2017-01-13 21:47 UTC
I was able to make it stop before it got to the top, chop it into two separate vines (break in the middle), and graphically show only one side.  See pic.  Sorry I forget which level, but it is definitely on the newest update.
![img_2500](https://cloud.githubusercontent.com/assets/6308005/21946766/eab5a1d8-d9af-11e6-8af1-5641d1d3f803.JPG)

**Comment by dahrkdaiz** [comment] 2017-01-15 16:53
When you did this, I assume you were moving to the left and back to the right real quick? Also, the break in the vine, was that just a graphical thing or was it physically not there?

**Comment by RetroMarine** [comment] 2017-01-15 21:08
Yes, and it was NOT just graphical.  I could not physically complete the climb without a jumping maneuver.

**Comment by dahrkdaiz** [comment] 2017-01-22 12:24
Okay, I've changed the code around to fix this issue, but, since it's hard to reproduce (essentially, the game needs to change a block on screen dynamically at the exact same time to happen), I'll leave it up to you guys to find it again :P

**Closed by dahrkdaiz** 2017-01-22 12:24 UTC
